name: New static project
markdown: redcarpet
pygments: false
port: 8000
exclude: ['node_modules', '.sass-cache', 'sass', '.gitignore', 'Gruntfile.js', 'package.json', 'README.md', 'csssrc', '*.sublime-project', '*.sublime-workspace']
